### ISSUE TITLE
No such file or directory...

### ISSUE THREAD

**Issue by ghost** [nahamsec/lazyrecon#45]
i did ./install.sh and done install all. But failed to launch ./lazyrecon.sh (im using wsl kali)
![image](https://user-images.githubusercontent.com/54031809/84461246-91d9c600-ac9e-11ea-8d87-9e05c0e2932b.png)

**Comment by skynet594** [comment]
@Teng-Zheng 
it's because you didn't move it to your home directory.
So change directory to the lazyrecon main directory where the script is located and use the following command.
sudo mv lazyrecon.sh /bin
This command will move it to the /bin directory so that you can run the script from anywhere.

I hope this helps.

**Comment by ghost** [comment]
I dont see i have the lazyrecon file

**Comment by skynet594** [comment]
@Teng-Zheng 
The .install.sh script you run helps to install all the other tools that lazyrecon depends on.
Meaning you would have to go to the following link below and following the instructions for the installation. When you are done, use the command in my previous reply to move it into the /bin directory.
https://github.com/nahamsec/lazyrecon

**Comment by skynet594** [comment]
You can look at the steps in the image below in case you are finding any difficulties.
![lazyrecon](https://user-images.githubusercontent.com/55256439/84492173-c5532b00-ac73-11ea-88f7-370e4fa0ae2a.png)

**Comment by ghost** [comment]
Im so sorry for wasting time for dummie like me , Thank you so much

**Comment by skynet594** [comment]
@Teng-Zheng 
You are welcome..
If you are okay then you can close the report.
